version: "3.8"

services:
  nginx:
    build: .
    container_name: awesome-nginx
    image: tomy0000000/nginx
    ports:
      - 80:80
      - 443:443
    restart: always
    networks:
      - proxy_bridge

networks:
  proxy_bridge:
