name: "Caddy Cloudflare"

on:
  push:
    paths:
      - "Dockerfiles/caddy-cloudflare/**"
      - "!Dockerfiles/caddy-cloudflare/README.md"
    branches:
      - "main"
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:
    inputs:
      base_tag:
        description: "Upstream caddy tag to build"
        required: true
        default: "latest"
        type: string

env:
  IMAGE_NAME: "caddy-cloudflare"

jobs:
  build:
    name: 🛠 Build
    runs-on: ubuntu-latest
    steps:
      - name: 🛒 Checkout
        uses: actions/checkout@v3

      - name: ⚙️ Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: ⚙️ Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: 🔑 Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: 🏗️ Build and push
        uses: docker/build-push-action@v3
        with:
          build-args: "BASE_TAG=${{ inputs.base_tag || 'latest' }}"
          context: Dockerfiles/${{ env.IMAGE_NAME }}
          push: true
          tags: ${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ inputs.base_tag || 'latest' }}
