name: "nginx"

on:
  workflow_dispatch:
    version:
      description: "Base image tag/version"
      required: false
      default: "latest"
  push:
    paths:
      - "Dockerfiles/nginx/**"
      - "!Dockerfiles/nginx/README.md"
      - ".github/workflows/nginx.yml"
    branches:
      - "*"
    tags:
      - "nginx"

jobs:
  latest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setting base image tag
        run: echo "BASE_TAG=$(echo ${{ github.event.inputs.version }})" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        if: ${{ startsWith(github.ref, 'refs/tags/') }}

      - name: Login to DockerHub
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to GitHub Container Registry
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: Dockerfiles/${{ github.workflow }}
          file: Dockerfiles/${{ github.workflow }}/Dockerfile
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/${{ github.workflow }}:latest
            ghcr.io/${{ github.repository_owner }}/${{ github.workflow }}:latest
          push: ${{ startsWith(github.ref, 'refs/tags/') }}
