name: "nginx"

on:
  push:
    paths:
      - "Dockerfiles/nginx/**"
      - "!Dockerfiles/nginx/README.md"
    branches:
      - "master"
    tags:
      - "nginx"

env:
  IMAGE_NAME: "nginx"

jobs:
  docker-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Convert tag to version
        run: echo ::set-env name=IMAGE_TAG::$(echo "${{ github.ref }}" | cut -d"/" -f3 | sed -En "s/^${{ env.IMAGE_NAME }}-(.*)/\1/p")
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
      - name: Login to DockerHub
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Login to GitHub Container Registry
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: Dockerfiles/${{ env.IMAGE_NAME }}
          file: Dockerfiles/${{ env.IMAGE_NAME }}/Dockerfile
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest
          push: ${{ startsWith(github.ref, 'refs/tags/') }}
