name: "Postgres Backup to Dropbox"

on:
  push:
    paths:
      - ".github/workflows/postgres-backup-dropbox.yml"
      - "Dockerfiles/postgres-backup-dropbox/**"
    branches:
      - "main"

env:
  TITLE: "Postgres Backup to Dropbox"
  DESCRIPTION: "Backup a postgres instance to Dropbox with `dbxcli`"
  IMAGE_NAME: "postgres-backup-dropbox"

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        postgres: ["11", "12", "13", "14", "latest"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ github.repository_owner }}/${{ env.IMAGE_NAME }}
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=${{ matrix.postgres }}
          labels: |
            maintainer=${{ github.repository_owner }}
            org.opencontainers.image.title=${{ env.TITLE }}
            org.opencontainers.image.description=${{ env.DESCRIPTION }}
            org.opencontainers.image.url=${{ github.repositoryUrl }}/tree/main/Dockerfiles/${{ env.IMAGE_NAME }}
            org.opencontainers.image.source=${{ github.repositoryUrl }}/tree/main/Dockerfiles/${{ env.IMAGE_NAME }}
            org.opencontainers.image.version=${{ matrix.postgres }}

      - name: Build and Push Image
        uses: tomy0000000/actions/build-push-image@main
        with:
          docker_password: ${{ secrets.DOCKER_PASSWORD }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          context: Dockerfiles/${{ env.IMAGE_NAME }}

  update-docker-hub-readme:
    name: "Update Docker Hub README"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Update repository description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ github.repository_owner }}/${{ env.IMAGE_NAME }}
          short-description: ${{ env.DESCRIPTION }}
          readme-filepath: Dockerfiles/${{ env.IMAGE_NAME }}/README.md
