name: "Redis 6.0"

on:
  push:
    paths:
      - "Dockerfiles/redis/**"
      - "!Dockerfiles/redis/README.md"
    branches:
      - "main"
    tags:
      - "redis-6.0-*"

env:
  IMAGE_NAME: "redis"
  BASE_VERSION: "6.0"

jobs:
  docker-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Convert tag to version
        run: echo ::set-env name=IMAGE_TAG::$(echo "${{ github.ref }}" | cut -d"/" -f3 | sed -En "s/^${{ env.IMAGE_NAME }}-(.*)/\1/p")
      - name: Build and Push to Docker Hub
        uses: docker/build-push-action@v3
        with:
          repository: ${{ github.repository_owner }}/${{ env.IMAGE_NAME }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: ${{ env.IMAGE_TAG }}
          path: Dockerfiles/${{ env.IMAGE_NAME }}/${{ env.BASE_VERSION }}
          push: ${{ startsWith(github.ref, 'refs/tags/') }}
  github-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Convert repository name to lowercase
        run: echo ::set-env name=GITHUB_REPOSITORY::$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')
      - name: Convert tag to version
        run: echo ::set-env name=IMAGE_TAG::$(echo "${{ github.ref }}" | cut -d"/" -f3 | sed -En "s/^${{ env.IMAGE_NAME }}-(.*)/\1/p")
      - name: Build and Push to Github Package
        uses: docker/build-push-action@v3
        with:
          repository: ${{ env.GITHUB_REPOSITORY }}/${{ env.IMAGE_NAME }}
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}
          registry: docker.pkg.github.com
          tags: ${{ env.IMAGE_TAG }}
          path: Dockerfiles/${{ env.IMAGE_NAME }}/${{ env.BASE_VERSION }}
          push: ${{ startsWith(github.ref, 'refs/tags/') }}
